services:
  app:
    build: .
    container_name: fast_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_CONNECTION=user:password@postgres:5432/wallets_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy


  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wallets_db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d wallets_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./cache:/root/redis
    networks:
      - app_network


networks:
  app_network:
    driver: bridge
